export const declutteringDummy = [
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bathroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_industrial_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_industrial_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_industrial_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_industrial_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_bedroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_italian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_italian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_italian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_italian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_mediterranean_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_mediterranean_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_mediterranean_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_mediterranean_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_traditional_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_traditional_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_traditional_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_kitchen_traditional_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_wooden_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_wooden_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_wooden_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/1_living room_wooden_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bathroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_industrial_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_industrial_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_industrial_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_industrial_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_bedroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_italian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_italian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_italian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_italian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_mediterranean_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_mediterranean_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_mediterranean_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_mediterranean_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_traditional_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_traditional_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_traditional_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_kitchen_traditional_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_wooden_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_wooden_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_wooden_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/2_living room_wooden_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bathroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_industrial_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_industrial_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_industrial_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_industrial_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_bedroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_italian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_italian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_italian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_italian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_mediterranean_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_mediterranean_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_mediterranean_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_mediterranean_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_traditional_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_traditional_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_traditional_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_kitchen_traditional_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_wooden_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_wooden_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_wooden_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/3_living room_wooden_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bathroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_industrial_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_industrial_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_industrial_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_industrial_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_bedroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_italian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_italian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_italian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_italian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_mediterranean_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_mediterranean_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_mediterranean_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_mediterranean_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_traditional_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_traditional_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_traditional_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_kitchen_traditional_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_wooden_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_wooden_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_wooden_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/4_living room_wooden_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bathroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_industrial_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_industrial_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_industrial_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_industrial_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_bedroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_italian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_italian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_italian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_italian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_mediterranean_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_mediterranean_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_mediterranean_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_mediterranean_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_traditional_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_traditional_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_traditional_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_kitchen_traditional_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_wooden_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_wooden_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_wooden_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/5_living room_wooden_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bathroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_industrial_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_industrial_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_industrial_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_industrial_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_bedroom_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_italian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_italian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_italian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_italian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_mediterranean_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_mediterranean_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_mediterranean_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_mediterranean_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_traditional_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_traditional_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_traditional_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_kitchen_traditional_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_coastal_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_coastal_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_coastal_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_coastal_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_contemporary_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_contemporary_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_contemporary_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_contemporary_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_modern_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_modern_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_modern_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_modern_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_rustic_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_rustic_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_rustic_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_rustic_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_scandinavian_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_scandinavian_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_scandinavian_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_scandinavian_4.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_wooden_1.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_wooden_2.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_wooden_3.jpg",
  "https://storage.googleapis.com/store-gallery-img-results/decluttering-gallery-results/6_living room_wooden_4.jpg",
];
