export const dummyImages = [
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bathroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_industrial_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_industrial_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_industrial_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_industrial_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_industrial_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_bedroom_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_italian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_italian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_italian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_italian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_italian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_traditional_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_traditional_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_traditional_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_kitchen_traditional_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_wooden_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_wooden_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_wooden_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_wooden_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bd551240_living room_wooden_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bathroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_industrial_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_industrial_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_industrial_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_industrial_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_industrial_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_bedroom_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_italian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_italian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_italian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_italian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_italian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_traditional_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_traditional_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_traditional_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_traditional_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_kitchen_traditional_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_wooden_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_wooden_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_wooden_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_wooden_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78bfd990ad_living room_wooden_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bathroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_industrial_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_industrial_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_industrial_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_industrial_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_industrial_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_bedroom_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_italian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_italian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_italian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_italian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_italian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_traditional_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_traditional_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_traditional_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_traditional_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_kitchen_traditional_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_wooden_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_wooden_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_wooden_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_wooden_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c21a71b3_living room_wooden_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bathroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_industrial_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_industrial_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_industrial_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_industrial_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_industrial_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_bedroom_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_italian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_italian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_italian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_italian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_italian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_traditional_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_traditional_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_traditional_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_traditional_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_kitchen_traditional_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_wooden_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_wooden_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_wooden_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_wooden_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c4c8ce08_living room_wooden_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bathroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_industrial_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_industrial_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_industrial_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_industrial_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_industrial_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_bedroom_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_italian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_italian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_italian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_italian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_italian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_traditional_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_traditional_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_traditional_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_traditional_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_kitchen_traditional_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_wooden_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_wooden_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_wooden_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_wooden_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/64b78c77d3232_living room_wooden_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bathroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_industrial_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_industrial_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_industrial_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_industrial_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_industrial_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_bedroom_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_italian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_italian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_italian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_italian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_italian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_mediterranean_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_mediterranean_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_mediterranean_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_mediterranean_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_mediterranean_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_traditional_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_traditional_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_traditional_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_traditional_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_kitchen_traditional_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_coastal_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_coastal_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_coastal_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_coastal_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_coastal_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_contemporary_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_contemporary_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_contemporary_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_contemporary_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_contemporary_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_modern_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_modern_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_modern_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_modern_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_modern_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_rustic_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_rustic_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_rustic_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_rustic_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_rustic_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_scandinavian_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_scandinavian_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_scandinavian_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_scandinavian_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_scandinavian_5.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_wooden_1.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_wooden_2.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_wooden_3.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_wooden_4.jpg",
"https://storage.googleapis.com/store-gallery-img-results/staging/virtual-staging-sample_living room_wooden_5.jpg",
];